### ISSUE TITLE
bluetooth_name is unavailable on API level >= 32

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-sdk-flutter#13]
https://github.com/react-native-device-info/react-native-device-info/issues/1463

**Comment by tung2744** [comment]
@louischan-oursky It seems flutter already applied this fix:
https://github.com/authgear/authgear-sdk-flutter/blob/main/android/src/main/kotlin/com/authgear/flutter/AuthgearPlugin.kt#L303-L309

**Comment by louischan-oursky** [comment]
So what we lack is just publish a new release.

**Comment by tung2744** [comment]
Should we just publish 1.0.1?

**Comment by louischan-oursky** [comment]
1.1.0 But I guess you do not have enough access to do that.

**Comment by louischan-oursky** [comment]
https://pub.dev/packages/flutter_authgear/versions/1.1.0
