### ISSUE TITLE
Build with Xcode 15.2 and Android Studio Giraffle

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/authgear-sdk-flutter#35]
From 2024-04-29, all apps must be built with iOS 17 SDK or later.

Currently this app can only be built with Android Studio Electric Eel.

**Comment by IniZio** [comment]
Note: Seems need to update react-native and capacitor as well

**Comment by louischan-oursky** [comment]
Actually, update all SDKs.

**Comment by IniZio** [comment]
Checked again other SDKs should already meet this baselne.
