### ISSUE TITLE
[flutter demo] `Instance of "OAuth Exception"` error when using biometric login

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-sdk-flutter#38]
In the demo app on iOS with biometric enabled,
An error message `Instance of "OAuth Exception"` is shown when I try to login with biometric.

I've tested the same project on other demo apps and they are ok.

![image](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/73d22731-c4d0-4dad-a36f-a1abf17de44f/e13f863b-05b2-45f3-afd5-a56ec17094b9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi83M2QyMjczMS1jNGQwLTRkYWQtYTM2Zi1hMWFiZjE3ZGU0NGYvZTEzZjg2M2ItMDViMi00NWYzLWFmZDUtYTU2ZWMxNzA5NGI5IiwiaWF0IjoxNzA5ODI2NTI1LCJleHAiOjMzMjgwMzg2NTI1fQ.M8Iu1zerKHjF59GpavQYJ-30_VRJvIs3g3iwvrksxdU)

**Comment by IniZio** [comment]
The OAuth exception originates from [https://github.com/authgear/authgear-server/blob/ac19ccbc3d4eb12da4db6bd1912294a754b0c849/pkg/lib/authn/identity/biometric/provider.go#L171](https://github.com/authgear/authgear-server/blob/ac19ccbc3d4eb12da4db6bd1912294a754b0c849/pkg/lib/authn/identity/biometric/provider.go#L171) where verification of jwt with given keyset failed

After swapping in iOS sdk's implementation and then removing gradually, found the only difference that caused this exception is in payload's serialization [https://github.com/authgear/authgear-sdk-flutter/blob/d8897ead2a3bc650a51eb993a273370342738472/ios/Classes/SwiftAuthgearPlugin.swift#L787](https://github.com/authgear/authgear-sdk-flutter/blob/d8897ead2a3bc650a51eb993a273370342738472/ios/Classes/SwiftAuthgearPlugin.swift#L787)

In IOS sdk, the serialization is done with encodable [https://github.com/authgear/authgear-sdk-ios/blob/7d9ccf0396ea6f111b8a1913c579ba3e3993dab5/Sources/JWT.swift#L85](https://github.com/authgear/authgear-sdk-ios/blob/7d9ccf0396ea6f111b8a1913c579ba3e3993dab5/Sources/JWT.swift#L85)

**Comment by louischan-oursky** [comment]
What is the key difference in the serialization?

**Comment by IniZio** [comment]
The minimal difference I created is this:

```swift
// iOS
struct JWTPayload: Encodable {
    let iat: Int
    let exp: Int
    let challenge: String
    let action: String

    enum CodingKeys: String, CodingKey {
        case iat
        case exp
        case challenge
        case action
    }

    init(challenge: String, action: String) {
        let now = Int(Date().timeIntervalSince1970)
        iat = now
        exp = now + 60
        self.challenge = challenge
        self.action = action
    }

    func encode() throws -> String {
        let jsonEncoder = JSONEncoder()
        let data = try jsonEncoder.encode(self)
        return data.base64EncodedString()
    }
}

let payload = Payload(challenge: "[challenge]", action: "authenticate")

// flutter
let payloadMap: [String: Any] = [
  "iat": payload.iat,
  "exp": payload.exp,
  "challenge": payload.challenge,
  "action": payload.action,
]

let swiftPayloadString = try payload.encode()
let flutterPayloadString = JSONSerialization.serialize(value: payloadMap).base64EncodedString()
```

All the key/values should be same after decoding the string except for the key ordering.

**Comment by IniZio** [comment]
Tested android again does not have this issue.

**Comment by fungc-io** [comment]
tested
